name: 'Get Users'
description: 'Gets all user logins from an organization'
inputs: 
  secret-token:
    description: 'auth token'
    required: true
outputs:
  user-logins:
    description: 'json object that holds all user logins'
    value: ${{ steps.login-getter.outputs.user-logins }}
runs:
  using: "composite"
  steps:
    - name: Checkout Current Repository
      uses: actions/checkout@v3

    - name: installing dependencies
      run: npm install
      shell: bash

    - name: Calling carsons query
      id: login-getter
      run: |
        node getUsers.js ${{ inputs.secret-token }}
        echo "user-logins=`cat outputs.json`" >> $GITHUB_OUTPUT
      shell: bash 
