name: Demo 1 Github Actions/APIs/workflows

on: 
  workflow_dispatch:
  workflow_call:

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Restoring cached dependencies 
      uses: actions/cache/restore@v3
      id: cache
      with:
        path: path/to/dependencies
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
        # exits workflow on a cache miss to avoid any errors
        fail-on-cache-miss: true
        
    - name: Get user logins from org
      run: node index.js
    
    - uses: actions/upload-artifact@v3
      with:
        name: logins
        path: output.json
    
    
