name: Demo 1 Github Actions/APIs/workflows

on: 
  workflow_dispatch:
  workflow_call:

jobs: 
  build: ubuntu-latest
  steps:
  - uses: actions/checkout@v3
  - uses: actions/setup-node@v3
    with:
      node-version: 16
      cache: 'npm'
  - run: npm ci
  - run: npm test
    
