name: Demo 1 Github Actions/APIs/workflows

on: 
  workflow_dispatch:
  workflow_call:

jobs: 
  Getting_User_logins:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Restoring cached dependencies 
      uses: actions/cache/restore@v3
      id: cache
      with:
        path: ~/.npm
        key: ${{ secrets.CACHE_KEY }}
        # exits workflow on a cache miss to avoid any errors
        fail-on-cache-miss: true
        
    - name: install octokit
      run: npm install octokit

    - name: Get user logins from org
      run: | 
        node index.js
        value=`cat output.json`
        echo $value
    - uses: actions/upload-artifact@v3
      with:
        name: logins
        path: output.json
    
