

    
name: Demo 1 Github Actions/APIs/workflows

on: 
#   push:
#     branches: 
#     - main
  workflow_dispatch:

jobs: 
  Getting_User_logins:
    runs-on: ubuntu-latest
    steps:

    # Ripping logins using composite actions
    - name: Get user logins using composite actions
      id: get-users
      env:
        SECRET_TOKEN: ${{ secrets.TOKEN }}
      uses: ImmortalHedgehogs/Demo1/getUsers@mainworkflow
      with:
        secret-token: $SECRET_TOKEN
      
    # placing output from composite action into output.json to upload artifact
    - run: echo ${{ steps.get-users.outputs.user-logins}} >> output.json



    # uploads user logins as an artifact 
    - uses: actions/upload-artifact@v3
      with:
        name: logins
        path: output.json
  
  create-repos:
    needs: Getting_User_logins
    uses: ImmortalHedgehogs/Demo1/.github/workflows/create-repos.yml@matrix-workflow
    secrets:
      inherit
